version: '3.3'

services:

  asr:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    restart: unless-stopped
    ports:
      - 8010:8000
    environment:
      - ASR_API_CONFIG=/app/config.json
      - MODELS_ROOT=/app/models
      - VOCABS_ROOT=/app/vocabularies
      # - PROXY_PREFIX=api  # Comment out in local
    container_name: asrapi
    networks:
      - api-network
      
networks:
  api-network:
    external: true

